# Workflow Name: Unified Release Rolling & Bananas
name: Rolling Release

# Trigger: Runs on push to the master branch OR on push of the 'bananas' tag
on:
  push:
    branches:
      - master
    tags:
      - 'bananas'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Prepare the release version using YYMMDD format
      - name: Prepare Release Version (YYMMDD)
        run: echo "VERSION=$(git log -1 --pretty=format:%cd --date=format:%y%m%d)" >> $GITHUB_ENV

      # Step 3: Generate dynamic release notes from Git history for all releases
      - name: Generate Dynamic Release Notes
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || git rev-list --max-parents=0 HEAD)
          CHANGELOG_BODY=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:'* %s')
          {
            echo "CHANGELOG_BODY<<EOF"
            echo -e "Changes since ${PREVIOUS_TAG}:\n"
            echo "${CHANGELOG_BODY}"
            echo "EOF"
          } >> "$GITHUB_ENV"
      
      # Step 4: Set up release parameters based on the trigger
      - name: Prepare Release Parameters
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "RELEASE_TAG_NAME=${{ env.VERSION }}" >> $GITHUB_ENV
            echo "RELEASE_NAME=Trans AI Rolling Release ${{ env.VERSION }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/tags/bananas" ]]; then
            echo "RELEASE_TAG_NAME=bananas" >> $GITHUB_ENV
            echo "RELEASE_NAME=Trans AI Release ${{ env.VERSION }} for Bananas Content Service" >> $GITHUB_ENV
          fi

      # Step 5: Prepare the staging directory
      - name: Prepare Staging Directory
        run: mkdir -p staging/Trans-AI_${{ env.VERSION }}

      # Step 6: Copy project files using git archive to respect .gitignore
      - name: Copy Project Files via Git Archive
        run: git archive --format=tar HEAD | tar -x -C staging/Trans-AI_${{ env.VERSION }}/

      # Step 7: Update the version number inside info.nut
      - name: Update Version in info.nut
        run: sed -i 's/return 200101/return ${{ env.VERSION }}/g' staging/Trans-AI_${{ env.VERSION }}/info.nut

      # Step 8: Create the final release archives (tar and zip)
      - name: Create Final Release Archives
        run: |
          cd staging
          tar -cf ../Trans-AI_${{ env.VERSION }}.tar Trans-AI_${{ env.VERSION }}
          zip -r ../Trans-AI_${{ env.VERSION }}.zip Trans-AI_${{ env.VERSION }}
          cd ..

      # Step 9: Create the GitHub Release using the prepared parameters
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          body: ${{ env.CHANGELOG_BODY }}
          files: |
            Trans-AI_${{ env.VERSION }}.tar
          make_latest: true